[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
ghost_vault = "AouRAHF6Cm2oqCNiJcV2Gg4Vzwyy5UeA3jnFYS5jJm4W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/anja/.config/solana/new.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
